version: '3'

services:
  backend:
    env_file:
        "./Server/.env"
    build:
      context: ./Server
      dockerfile: ./Dockerfile
    image: "portfolio/server"
    ports:
      - "8081:5000"
    mem_limit: 2g
  frontend:
    env_file:
        "./Client/.env.production"
    build:
      context: ./Client
      dockerfile: ./Dockerfile
    image: "portfolio/client"
    ports:
      - "8080:3000"
    mem_limit: 2g